### ISSUE TITLE
Cant use DockerContainer infrastructure even when agent can access docker sock

### ISSUE THREAD

**Issue by cakir-enes** [rpeden/prefect-docker-compose#8]
Added this to agents docker-compose yml
```
volumes:
	- "/var/run/docker.sock:/var/run/docker.sock"
```

Created this file (`log_flows.py`) under `flows` dir
```
from prefect import flow, task
from prefect.deployments import Deployment
from prefect.infrastructure import DockerContainer


@task
def say_hello(name):
    print(f"hello {name}")

@task
def say_goodbye(name):
    print(f"goodbye {name}")

@flow(name="test flow")
def greetings(names=["arthur", "trillian", "ford", "marvin"]):
    for name in names:
        say_hello(name)
        say_goodbye(name)

if __name__ == "__main__":
    #greetings(["arthur", "trillian", "ford", "marvin"])
    a = Deployment.build_from_flow(
                    greetings, "ecs", apply=True, infrastructure=DockerContainer(auto_remove=False,name="failing"),work_queue_name="ecs"
                        )
```

Entered shell via `docker compose run cli` then executed `python log_flows.py` which creates the deployment fine,  also I think docker connections works fine as well since when I try to enter gibberish for image name it fails with a meaningful error "no image found".  

When triggering run from the ui it fails with `Flow run infrastructure exited with non-zero status code 1.` no other logs, no docker image on `docker ps` to check.

**Comment by rpeden** [comment]
Apologies for the slow reply. Do you see any output from the agent when that happens? I'll experiment a bit to try and reproduce this. The first thing that comes to mind is perhaps a permission error; the host machine's Docker socket might not be  allowing the API call from the `DockerContainer` infrastructure block running inside the agent container.

**Comment by rpeden** [comment]
Closing for now, but will re-open if this comes up again.
